const featuredListings = [
    { 
        id: 1, 
        price: 150000, 
        location: 'Pécs, Damjanich u.', 
        images: ['képek/Damjanich u/Damjanich1.jpg', 'képek/Damjanich u/Damjanich2.jpg', 'képek/Damjanich u/Damjanich3.jpg', 'képek/Damjanich u/Damjanich4.jpg', 
                    'képek/Damjanich u/Damjanich5.jpg', 'képek/Damjanich u/Damjanich6.jpg', 'képek/Damjanich u/Damjanich7.jpg', 'képek/Damjanich u/Damjanich8.jpg'],
        buildingType: 'Lakás', 
        deposit: 600000, 
        utilityCost: 70000, 
        heating: 'Központi', 
        furnishing: 'Üres, gépesített', 
        rooms: 3, 
        floor: 1, 
        view: 'Panorámás', 
        balconies: 'Van', 
        americankitchen: 'Van'
    },
    { 
        id: 2, 
        price: 160000, 
        location: 'Pécs, Építők útja', 
        images: ['képek/Epitok u/Epitok1.jpg', 'képek/Epitok u/Epitok2.jpg', 'képek/Epitok u/Epitok3.jpg', 'képek/Epitok u/Epitok4.jpg', 'képek/Epitok u/Epitok5.jpg',
                    'képek/Epitok u/Epitok6.jpg', 'képek/Epitok u/Epitok7.jpg', ], 
        buildingType: 'Családi ház', 
        deposit: 900000, 
        utilityCost: 90000, 
        heating: 'Hőszivattyú', 
        furnishing: 'Berendezett, gépesített', 
        rooms: 4, 
        floor: 'Egyszintes', 
        view: 'Panorámás', 
        balconies: 'Van', 
        americankitchen: 'Van'
    },
    { 
        id: 3, 
        price: 90000, 
        location: 'Pécs, Gadó u.', 
        images: ['képek/Gado u/Gado1.jpg', 'képek/Gado u/Gado2.jpg', 'képek/Gado u/Gado3.jpg', 'képek/Gado u/Gado4.jpg'], 
        buildingType: 'Lakás', 
        deposit: 300000, 
        utilityCost: 50000, 
        heating: 'Központi', 
        furnishing: 'Üres, gépesített', 
        rooms: 1.5, 
        floor: 7, 
        view: 'Utcai', 
        balconies: 'Nincs', 
        americankitchen: 'Nincs' 
    },
    { 
        id: 4, 
        price: 250000, 
        location: 'Pécs, Avar u.', 
        images: ['képek/Avar u/Avar1.jpg', 'képek/Avar u/Avar2.jpg', 'képek/Avar u/Avar3.jpg', 'képek/Avar u/Avar4.jpg', 'képek/Avar u/Avar5.jpg',
                    'képek/Avar u/Avar6.jpg', 'képek/Avar u/Avar7.jpg', 'képek/Avar u/Avar8.jpg'], 
        buildingType: 'Családi ház', 
        deposit: 1200000, 
        utilityCost: 100000, 
        heating: 'Cirkó', 
        furnishing: 'Berendezett', 
        rooms: 3.5, 
        floor: 'Kétszintes', 
        view: 'Panorámás', 
        balconies: 'Van', 
        americankitchen: 'Van' 
    },
    { 
        id: 5, 
        price: 125000, 
        location: 'Pécs, Alsó u.', 
        images: ['képek/Also u/Also1.jpg', 'képek/Also u/Also2.jpg', 'képek/Also u/Also3.jpg', 'képek/Also u/Also4.jpg', 'képek/Also u/Also5.jpg', 'képek/Also u/Also6.jpg'],  
        buildingType: 'Családi ház', 
        deposit: 550000, 
        utilityCost: 80000, 
        heating: 'Hőszivattyú', 
        furnishing: 'Üres, gépesített', 
        rooms: 3, 
        floor: 'Kétszintes', 
        view: 'Panorámás', 
        balconies: 'Van', 
        americankitchen: 'Nincs' 
    },
    { 
        id: 6, 
        price: 70000, 
        location: 'Pécs, Páfrány u.', 
        images: ['képek/Pafrany u/Pafrany1.jpg', 'képek/Pafrany u/Pafrany2.jpg', 'képek/Pafrany u/Pafrany3.jpg', 'képek/Pafrany u/Pafrany4.jpg',
                    'képek/Pafrany u/Pafrany5.jpg', 'képek/Pafrany u/Pafrany6.jpg', 'képek/Pafrany u/Pafrany7.jpg', 'képek/Pafrany u/Pafrany8.jpg',
                    'képek/Pafrany u/Pafrany9.jpg'], 
        buildingType: 'Lakás', 
        deposit: 250000, 
        utilityCost: 40000, 
        heating: 'Cirkó', 
        furnishing: 'Üres', 
        rooms: 2, 
        floor: 9, 
        view: 'Utcai', 
        balconies: 'Nincs', 
        americankitchen: 'Nincs' 
    },
    { 
        id: 7, 
        price: 350000, 
        location: 'Pécs, Sas dűlő', 
        images: ['képek/Sas dulo/Sas dulo1.jpg', 'képek/Sas dulo/Sas dulo2.jpg', 'képek/Sas dulo/Sas dulo3.jpg', 'képek/Sas dulo/Sas dulo4.jpg',
                    'képek/Sas dulo/Sas dulo5.jpg', 'képek/Sas dulo/Sas dulo6.jpg', 'képek/Sas dulo/Sas dulo7.jpg'], 
        buildingType: 'Családi ház', 
        deposit: 1500000, 
        utilityCost: 120000, 
        heating: 'Hőszivattyú', 
        furnishing: 'Berendezett, gépesített', 
        rooms: 4, 
        floor: 'Kétszintes', 
        view: 'Panorámás', 
        balconies: 'Van', 
        americankitchen: 'Van' 
    },
    { 
        id: 8, 
        price: 130000, 
        location: 'Pécs, Pacsirta u.', 
        images: ['képek/Pacsirta u/Pacsirta1.jpg', 'képek/Pacsirta u/Pacsirta2.jpg', 'képek/Pacsirta u/Pacsirta3.jpg', 'képek/Pacsirta u/Pacsirta4.jpg',
                    'képek/Pacsirta u/Pacsirta5.jpg'],
        buildingType: 'Lakás', 
        deposit: 480000, 
        utilityCost: 75000, 
        heating: 'Központi', 
        furnishing: 'Berendezett, gépesített', 
        rooms: 2, 
        floor: 3, 
        view:'Utcai, világos', 
        balconies: 'Van', 
        americankitchen: 'Nincs' 
    },
    { 
        id: 9, 
        price: 350000, 
        location: 'Pécs, Hordós dűlő', 
        images: ['képek/Hordos dulo/Hordos1.jpg', 'képek/Hordos dulo/Hordos2.jpg', 'képek/Hordos dulo/Hordos3.jpg', 'képek/Hordos dulo/Hordos4.jpg',
                    'képek/Hordos dulo/Hordos5.jpg'],
        buildingType: 'Családi ház', 
        deposit: 1200000, 
        utilityCost: 120000, 
        heating: 'Központi', 
        furnishing: 'Berendezett, gépesített', 
        rooms: 4, 
        floor: 'Egyszintes', 
        view:'Panorámás', 
        balconies: 'Van', 
        americankitchen: 'Nincs' 
    },
    { 
        id: 10, 
        price: 170000, 
        location: 'Pécs, Jedlik Ányos utca', 
        images: ['képek/Jedlik Anyos u/Jedlik1.jpg', 'képek/Jedlik Anyos u/Jedlik2.jpg', 'képek/Jedlik Anyos u/Jedlik3.jpg', 'képek/Jedlik Anyos u/Jedlik4.jpg',
                    'képek/Jedlik Anyos u/Jedlik5.jpg', 'képek/Jedlik Anyos u/Jedlik6.jpg', 'képek/Jedlik Anyos u/Jedlik7.jpg'],
        buildingType: 'Lakás', 
        deposit: 400000, 
        utilityCost: 80000, 
        heating: 'Központi', 
        furnishing: 'Berendezett, gépesített', 
        rooms: 3, 
        floor: 2, 
        view:'Utcai, panorámás', 
        balconies: 'Van', 
        americankitchen: 'Nincs' 
    },
    { 
        id: 11, 
        price: 150000, 
        location: 'Pécs, Magyar Lajos utca', 
        images: ['képek/Magyar Lajos u/Magyar1.jpg', 'képek/Magyar Lajos u/Magyar2.jpg', 'képek/Magyar Lajos u/Magyar3.jpg', 'képek/Magyar Lajos u/Magyar4.jpg',
                    'képek/Magyar Lajos u/Magyar5.jpg', 'képek/Magyar Lajos u/Magyar6.jpg'],
        buildingType: 'Lakás', 
        deposit: 300000, 
        utilityCost: 60000, 
        heating: 'Központi', 
        furnishing: 'Üres', 
        rooms: 1, 
        floor: 3, 
        view:'Utcai, panorámás', 
        balconies: 'Nincs', 
        americankitchen: 'Nincs' 
    },
    { 
        id: 12, 
        price: 350000, 
        location: 'Pécs, Baranya utca', 
        images: ['képek/Baranya u/Baranya1.jpg', 'képek/Baranya u/Baranya2.jpg', 'képek/Baranya u/Baranya3.jpg', 'képek/Baranya u/Baranya4.jpg',
                    'képek/Baranya u/Baranya5.jpg', 'képek/Baranya u/Baranya6.jpg', 'képek/Baranya u/Baranya7.jpg'],
        buildingType: 'Lakás', 
        deposit: 700000, 
        utilityCost: 110000, 
        heating: 'Központi', 
        furnishing: 'Berendezett, gépesített', 
        rooms: 2, 
        floor: 1, 
        view:'Panorámás', 
        balconies: 'Van', 
        americankitchen: 'Van' 
    },
    { 
        id: 13, 
        price: 115000, 
        location: 'Pécs, Bánki Donát utca', 
        images: ['képek/Banki Donat u/Banki1.jpg', 'képek/Banki Donat u/Banki2.jpg', 'képek/Banki Donat u/Banki3.jpg', 'képek/Banki Donat u/Banki4.jpg',
                    'képek/Banki Donat u/Banki5.jpg'],
        buildingType: 'Lakás', 
        deposit: 250000, 
        utilityCost: 63000, 
        heating: 'Cirkó', 
        furnishing: 'Részben berendezett', 
        rooms: 1.5, 
        floor: 4, 
        view:'Utcai, panorámás', 
        balconies: 'Nincs', 
        americankitchen: 'Nincs' 
    },
    { 
        id: 14, 
        price: 85000, 
        location: 'Pécs, Nagy Imre utca', 
        images: ['képek/Nagy Imre u/Nagy1.jpg', 'képek/Nagy Imre u/Nagy2.jpg', 'képek/Nagy Imre u/Nagy3.jpg', 'képek/Nagy Imre u/Nagy4.jpg',
                    'képek/Nagy Imre u/Nagy5.jpg', 'képek/Nagy Imre u/Nagy6.jpg'],
        buildingType: 'Lakás', 
        deposit: 170000, 
        utilityCost: 50000, 
        heating: 'Cirkó', 
        furnishing: 'Részben berendezett', 
        rooms: 1, 
        floor: 8, 
        view:'Utcai, panorámás', 
        balconies: 'Nincs', 
        americankitchen: 'Nincs' 
    },
    { 
        id: 15, 
        price: 130000, 
        location: 'Pécs, Tildy Zoltán utca', 
        images: ['képek/Tildy Zoltan u/Tildy1.jpg', 'képek/Tildy Zoltan u/Tildy2.jpg', 'képek/Tildy Zoltan u/Tildy3.jpg', 'képek/Tildy Zoltan u/Tildy4.jpg',
                    'képek/Tildy Zoltan u/Tildy5.jpg', 'képek/Tildy Zoltan u/Tildy6.jpg'],
        buildingType: 'Lakás', 
        deposit: 170000, 
        utilityCost: 50000, 
        heating: 'Központi', 
        furnishing: 'Berendezett, gépesített', 
        rooms: 1, 
        floor: 2, 
        view:'Utcai, panorámás', 
        balconies: 'Nincs', 
        americankitchen: 'Nincs' 
    },
    { 
        id: 16, 
        price: 19500, 
        location: 'Pécs, Árnyas utca', 
        images: ['képek/Arnyas u/Arnyas1.jpg', 'képek/Arnyas u/Arnyas2.jpg', 'képek/Arnyas u/Arnyas3.jpg', 'képek/Arnyas u/Arnyas4.jpg',
                    'képek/Arnyas u/Arnyas5.jpg', 'képek/Arnyas u/Arnyas6.jpg'],
        buildingType: 'Lakás', 
        deposit: 450000, 
        utilityCost: 90000, 
        heating: 'Központi', 
        furnishing: 'Berendezett, gépesített', 
        rooms: 3, 
        floor: 2, 
        view:'Utcai, panorámás', 
        balconies: 'Van', 
        americankitchen: 'Van' 
    },
    { 
        id: 17, 
        price: 240000, 
        location: 'Pécs, Benke dűlő', 
        images: ['képek/Benke dulo/Benke1.jpg', 'képek/Benke dulo/Benke2.jpg', 'képek/Benke dulo/Benke3.jpg', 'képek/Benke dulo/Benke4.jpg',
                    'képek/Benke dulo/Benke5.jpg', 'képek/Benke dulo/Benke6.jpg', 'képek/Benke dulo/Benke7.jpg'],
        buildingType: 'Családi ház', 
        deposit: 600000, 
        utilityCost: 120000, 
        heating: 'Központi', 
        furnishing: 'Berendezett, gépesített', 
        rooms: 4, 
        floor: 'Egyszintes', 
        view:'Kerte néző', 
        balconies: 'Van', 
        americankitchen: 'Nincs' 
    },
];